# Generated by Django 3.2.3 on 2024-11-04 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Укажите время больше 1 мин.')], verbose_name='Время приготовления (мин)'),
        ),
    ]
