# Generated by Django 3.2.3 on 2024-10-21 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipeshorturl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeshorturl',
            options={'default_related_name': 'short_links', 'verbose_name': 'Короткая ссылка', 'verbose_name_plural': 'Короткие ссылки'},
        ),
        migrations.AlterField(
            model_name='recipeshorturl',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_links', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='recipeshorturl',
            constraint=models.UniqueConstraint(fields=('recipe', 'short_url'), name='unique_recipe_short_url'),
        ),
    ]
