# Generated by Django 3.2.3 on 2024-10-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20241021_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeshorturl',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_links', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
