# Generated by Django 3.2.3 on 2024-10-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipeshorturl_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeshorturl',
            name='full_url',
            field=models.URLField(default=1, verbose_name='Полная ссылка'),
            preserve_default=False,
        ),
    ]
